### ISSUE TITLE
Error running the roc.py file

### ISSUE THREAD

**Issue by sidsidsidsid** [XanaduAI/quantum-neural-networks#6]
I'm getting a latex error when attempting to run the roc.py code. I installed latex, but the problem is still persisting. Any help would be appreciated. Thanks.

***ENV:*****
Colab
!pip install strawberryfields==0.11.0 tensorflow==1.3.0
set to GPU

****COMMAND RAN****
!python roc.py

********ERROR MESSAGE:*********************************
Area under ROC curve: 0.5882831367606355
Closest threshold to optimal ROC: 0.46
Traceback (most recent call last):
  File "roc.py", line 76, in <module>
    plt.savefig('./roc.pdf')
  File "/usr/local/lib/python3.6/dist-packages/matplotlib/pyplot.py", line 689, in savefig
    res = fig.savefig(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/matplotlib/figure.py", line 2094, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/matplotlib/backend_bases.py", line 2075, in print_figure
    **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/matplotlib/backends/backend_pdf.py", line 2565, in print_pdf
    self.figure.draw(renderer)
  File "/usr/local/lib/python3.6/dist-packages/matplotlib/artist.py", line 50, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/matplotlib/figure.py", line 1649, in draw
    renderer, self, artists, self.suppressComposite)
  File "/usr/local/lib/python3.6/dist-packages/matplotlib/image.py", line 138, in _draw_list_compositing_images
    a.draw(renderer)
  File "/usr/local/lib/python3.6/dist-packages/matplotlib/artist.py", line 50, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/matplotlib/axes/_base.py", line 2628, in draw
    mimage._draw_list_compositing_images(renderer, self, artists)
  File "/usr/local/lib/python3.6/dist-packages/matplotlib/image.py", line 138, in _draw_list_compositing_images
    a.draw(renderer)
  File "/usr/local/lib/python3.6/dist-packages/matplotlib/artist.py", line 50, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/matplotlib/axis.py", line 1187, in draw
    renderer)
  File "/usr/local/lib/python3.6/dist-packages/matplotlib/axis.py", line 1125, in _get_tick_bboxes
    extent = tick.label1.get_window_extent(renderer)
  File "/usr/local/lib/python3.6/dist-packages/matplotlib/text.py", line 930, in get_window_extent
    bbox, info, descent = self._get_layout(self._renderer)
  File "/usr/local/lib/python3.6/dist-packages/matplotlib/text.py", line 304, in _get_layout
    ismath=False)
  File "/usr/local/lib/python3.6/dist-packages/matplotlib/backends/backend_pdf.py", line 2126, in get_text_width_height_descent
    renderer=self)
  File "/usr/local/lib/python3.6/dist-packages/matplotlib/texmanager.py", line 464, in get_text_width_height_descent
    dvifile = self.make_dvi(tex, fontsize)
  File "/usr/local/lib/python3.6/dist-packages/matplotlib/texmanager.py", line 328, in make_dvi
    texfile], tex)
  File "/usr/local/lib/python3.6/dist-packages/matplotlib/texmanager.py", line 298, in _run_checked_subprocess
    stderr=subprocess.STDOUT)
  File "/usr/lib/python3.6/subprocess.py", line 356, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.6/subprocess.py", line 423, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1364, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'latex': 'latex'

**Comment by co9olguy** [comment]
@sidsidsidsid it looks like it is trying to generate a pdf figure, but running into problems when doing so (likely it is trying to add an equation and can't find the required `latex` program on your system. 

Three suggestions:
- comment out the line `plt.savefig(...)`
- change `plt.savefig('./roc.pdf')` to `plt.savefig('./roc.png')`
- install `latex` on your system (`apt install texlive` or `sudo apt install texlive` on linux)

**Comment by trbromley** [comment]
@sidsidsidsid 
Another suggestion is to remove line 61 of `roc.py`:
`plt.rc('text', usetex=True)`
This line indicates to use text rendering with Latex (https://matplotlib.org/3.1.1/tutorials/text/usetex.html) and you should be able to remove.

**Comment by sidsidsidsid** [comment]
Thanks @co9olguy and @trbromley for the help. I removed line 61 of roc.py and it appears to have work. Again thanks to you both for all the suggestions.
